from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from database import get_db
from models import MissingPerson, Alert, User
from routes.auth import require_officer
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, Image
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfgen import canvas as pdfcanvas
from datetime import datetime
import os, tempfile, requests as req

router = APIRouter()

# ── Color palette ─────────────────────────────────────────────
DARK_BLUE  = colors.HexColor('#1e3a5f')
MED_BLUE   = colors.HexColor('#2563eb')
LIGHT_BLUE = colors.HexColor('#eff6ff')
RED        = colors.HexColor('#dc2626')
LIGHT_RED  = colors.HexColor('#fef2f2')
GREEN      = colors.HexColor('#16a34a')
LIGHT_GREEN= colors.HexColor('#f0fdf4')
GRAY       = colors.HexColor('#6b7280')
LIGHT_GRAY = colors.HexColor('#f9fafb')
BORDER     = colors.HexColor('#e5e7eb')
WHITE      = colors.white
BLACK      = colors.HexColor('#111827')


def download_image(url: str, base_url: str = "http://localhost:8000") -> str | None:
    """Download an image from URL and save to temp file. Returns temp file path."""
    if not url:
        return None
    try:
        full_url = url if url.startswith("http") else f"{base_url}{url}"
        response = req.get(full_url, timeout=5)
        if response.status_code == 200:
            ext = url.split(".")[-1].lower()
            if ext not in ["jpg", "jpeg", "png", "gif"]:
                ext = "jpg"
            tmp = tempfile.NamedTemporaryFile(
                delete=False, suffix=f".{ext}"
            )
            tmp.write(response.content)
            tmp.close()
            return tmp.name
    except Exception as e:
        print(f"[PDF] Image download failed: {e}")
    return None


def header_footer(canvas, doc):
    """Draw header and footer on every page."""
    canvas.saveState()
    w, h = A4

    # ── Header bar ────────────────────────────────────────────
    canvas.setFillColor(DARK_BLUE)
    canvas.rect(0, h - 55, w, 55, fill=1, stroke=0)

    # Shield icon (simple polygon)
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 18)
    canvas.drawString(20*mm, h - 37, "🛡")

    # Title
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(35*mm, h - 30, "FACEGUARD")
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor('#93c5fd'))
    canvas.drawString(35*mm, h - 42, "Surveillance & Communication System")

    # Right side — date
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica", 8)
    date_str = datetime.now().strftime("%d %b %Y, %I:%M %p")
    canvas.drawRightString(w - 15*mm, h - 28, f"Generated: {date_str}")
    canvas.drawRightString(w - 15*mm, h - 40, "CONFIDENTIAL — Police Use Only")

    # ── Footer ────────────────────────────────────────────────
    canvas.setFillColor(LIGHT_GRAY)
    canvas.rect(0, 0, w, 20*mm, fill=1, stroke=0)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(15*mm, 20*mm, w - 15*mm, 20*mm)

    canvas.setFillColor(GRAY)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(15*mm, 13*mm,
        "This document is generated by FaceGuard — Jaipur Engineering College & Research Centre, Dept. of CSE")
    canvas.drawString(15*mm, 8*mm,
        "CONFIDENTIAL: For authorized police personnel only. Unauthorized use is punishable by law.")
    canvas.drawRightString(w - 15*mm, 10*mm,
        f"Page {doc.page}")

    canvas.restoreState()


def build_styles():
    """Return a dict of paragraph styles."""
    base = getSampleStyleSheet()
    return {
        "section_title": ParagraphStyle(
            "section_title",
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=DARK_BLUE,
            spaceAfter=6,
            spaceBefore=4,
        ),
        "label": ParagraphStyle(
            "label",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            textColor=GRAY,
            spaceAfter=1,
        ),
        "value": ParagraphStyle(
            "value",
            fontName="Helvetica",
            fontSize=10,
            textColor=BLACK,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=9.5,
            textColor=BLACK,
            leading=14,
            spaceAfter=6,
        ),
        "small": ParagraphStyle(
            "small",
            fontName="Helvetica",
            fontSize=8,
            textColor=GRAY,
        ),
        "status_missing": ParagraphStyle(
            "status_missing",
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=RED,
        ),
        "status_found": ParagraphStyle(
            "status_found",
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=GREEN,
        ),
    }


@router.get("/person/{person_id}")
def generate_person_report(
    person_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_officer)
):
    """Generate a full PDF report for a missing person case."""

    # ── Fetch data ────────────────────────────────────────────
    person = db.query(MissingPerson).filter(
        MissingPerson.id == person_id
    ).first()
    if not person:
        raise HTTPException(status_code=404, detail="Person not found")

    alerts = db.query(Alert).filter(
        Alert.person_id == person_id
    ).order_by(Alert.created_at.desc()).all()

    styles = build_styles()
    story  = []
    w, h   = A4
    usable_w = w - 40*mm  # usable width after margins

    tmp_photo = None

    # ── Case reference ────────────────────────────────────────
    case_ref = f"FG-{datetime.now().year}-{person_id:04d}"
    reported = person.created_at.strftime("%d %B %Y") if person.created_at else "Unknown"

    # ── Section 1: Case header banner ────────────────────────
    status_color = RED if person.status == "missing" else GREEN
    status_bg    = LIGHT_RED if person.status == "missing" else LIGHT_GREEN

    banner_data = [[
        Paragraph(f"CASE REFERENCE: {case_ref}", ParagraphStyle(
            "ref", fontName="Helvetica-Bold", fontSize=11,
            textColor=DARK_BLUE
        )),
        Paragraph(
            f"STATUS: {person.status.upper()}",
            ParagraphStyle("st", fontName="Helvetica-Bold",
                           fontSize=11, textColor=status_color,
                           alignment=TA_RIGHT)
        )
    ]]
    banner_table = Table(banner_data, colWidths=[usable_w*0.6, usable_w*0.4])
    banner_table.setStyle(TableStyle([
        ('BACKGROUND',  (0,0), (-1,-1), LIGHT_BLUE),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [LIGHT_BLUE]),
        ('BOX',         (0,0), (-1,-1), 0.5, MED_BLUE),
        ('TOPPADDING',  (0,0), (-1,-1), 10),
        ('BOTTOMPADDING',(0,0),(-1,-1), 10),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING',(0,0), (-1,-1), 12),
        ('VALIGN',      (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(banner_table)
    story.append(Spacer(1, 12))

    # ── Section 2: Personal details + photo ──────────────────
    story.append(Paragraph("Personal Information", styles["section_title"]))
    story.append(HRFlowable(
        width=usable_w, thickness=0.5,
        color=BORDER, spaceAfter=8
    ))

    # Try to download person photo
    tmp_photo = download_image(person.photo_url) if person.photo_url else None

    def info_row(label, value):
        return [
            Paragraph(label, styles["label"]),
            Paragraph(str(value) if value else "Not provided", styles["value"])
        ]

    personal_rows = [
        info_row("Full Name",          person.name),
        info_row("Age",                f"{person.age} years" if person.age else None),
        info_row("Gender",             person.gender),
        info_row("Last Seen Location", person.last_seen_location),
        info_row("Contact Number",     person.contact_number),
        info_row("Date Reported",      reported),
        info_row("Total Alerts",       len(alerts)),
    ]

    # Two-column layout: details on left, photo on right
    if tmp_photo:
        try:
            photo_img = Image(tmp_photo, width=45*mm, height=55*mm)
            photo_img.hAlign = 'CENTER'

            details_table = Table(personal_rows, colWidths=[35*mm, usable_w*0.5 - 35*mm])
            details_table.setStyle(TableStyle([
                ('VALIGN',  (0,0), (-1,-1), 'TOP'),
                ('TOPPADDING', (0,0), (-1,-1), 3),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
            ]))

            outer = Table(
                [[details_table, photo_img]],
                colWidths=[usable_w*0.62, usable_w*0.38]
            )
            outer.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('RIGHTPADDING', (0,0), (0,-1), 10),
            ]))
            story.append(outer)
        except Exception:
            # Photo failed — just show details
            t = Table(personal_rows, colWidths=[38*mm, usable_w - 38*mm])
            t.setStyle(TableStyle([
                ('VALIGN',  (0,0), (-1,-1), 'TOP'),
                ('TOPPADDING', (0,0), (-1,-1), 3),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3),
            ]))
            story.append(t)
    else:
        t = Table(personal_rows, colWidths=[38*mm, usable_w - 38*mm])
        t.setStyle(TableStyle([
            ('VALIGN',  (0,0), (-1,-1), 'TOP'),
            ('TOPPADDING', (0,0), (-1,-1), 3),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        story.append(t)

    story.append(Spacer(1, 14))

    # ── Section 3: Description ────────────────────────────────
    if person.description:
        story.append(Paragraph("Case Description", styles["section_title"]))
        story.append(HRFlowable(width=usable_w, thickness=0.5, color=BORDER, spaceAfter=6))
        desc_table = Table(
            [[Paragraph(person.description, styles["body"])]],
            colWidths=[usable_w]
        )
        desc_table.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), LIGHT_GRAY),
            ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
            ('TOPPADDING',    (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING',   (0,0), (-1,-1), 12),
            ('RIGHTPADDING',  (0,0), (-1,-1), 12),
        ]))
        story.append(desc_table)
        story.append(Spacer(1, 14))

    # ── Section 4: Alert history ──────────────────────────────
    story.append(Paragraph(
        f"Alert History ({len(alerts)} record{'s' if len(alerts) != 1 else ''})",
        styles["section_title"]
    ))
    story.append(HRFlowable(width=usable_w, thickness=0.5, color=BORDER, spaceAfter=8))

    if not alerts:
        no_alert_table = Table(
            [[Paragraph("No face match alerts have been recorded for this case yet.",
                        styles["body"])]],
            colWidths=[usable_w]
        )
        no_alert_table.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), LIGHT_GRAY),
            ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
            ('TOPPADDING',    (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING',   (0,0), (-1,-1), 12),
        ]))
        story.append(no_alert_table)
    else:
        # Table headers
        alert_headers = [
            Paragraph("Alert ID", styles["label"]),
            Paragraph("Date & Time", styles["label"]),
            Paragraph("Location", styles["label"]),
            Paragraph("Camera", styles["label"]),
            Paragraph("Confidence", styles["label"]),
            Paragraph("Status", styles["label"]),
        ]

        alert_rows = [alert_headers]
        for i, a in enumerate(alerts):
            conf_val  = a.confidence or 0
            conf_color = (
                RED   if conf_val >= 85 else
                colors.HexColor('#d97706') if conf_val >= 70 else
                MED_BLUE
            )
            stat_color = (
                RED   if a.status == "new" else
                GREEN if a.status == "reviewed" else
                GRAY
            )
            row = [
                Paragraph(f"#{a.id}", styles["body"]),
                Paragraph(
                    a.created_at.strftime("%d %b %Y\n%I:%M %p")
                    if a.created_at else "—",
                    styles["body"]
                ),
                Paragraph(a.location or "Unknown", styles["body"]),
                Paragraph(a.camera_id or "—", styles["body"]),
                Paragraph(
                    f"{conf_val:.1f}%",
                    ParagraphStyle("conf", fontName="Helvetica-Bold",
                                   fontSize=9.5, textColor=conf_color)
                ),
                Paragraph(
                    (a.status or "new").capitalize(),
                    ParagraphStyle("stat", fontName="Helvetica-Bold",
                                   fontSize=9.5, textColor=stat_color)
                ),
            ]
            alert_rows.append(row)

        col_w = [
            usable_w*0.08,
            usable_w*0.20,
            usable_w*0.25,
            usable_w*0.15,
            usable_w*0.15,
            usable_w*0.17,
        ]
        alert_table = Table(alert_rows, colWidths=col_w, repeatRows=1)

        row_styles = [
            ('BACKGROUND',    (0,0), (-1, 0), DARK_BLUE),
            ('TEXTCOLOR',     (0,0), (-1, 0), WHITE),
            ('FONTNAME',      (0,0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE',      (0,0), (-1, 0), 8.5),
            ('TOPPADDING',    (0,0), (-1,-1), 7),
            ('BOTTOMPADDING', (0,0), (-1,-1), 7),
            ('LEFTPADDING',   (0,0), (-1,-1), 8),
            ('RIGHTPADDING',  (0,0), (-1,-1), 8),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
            ('GRID',          (0,0), (-1,-1), 0.3, BORDER),
            ('ROWBACKGROUNDS',(0,1), (-1,-1), [WHITE, LIGHT_GRAY]),
        ]

        # Highlight critical alerts
        for i, a in enumerate(alerts, start=1):
            if a.confidence and a.confidence >= 85 and a.status == "new":
                row_styles.append(
                    ('BACKGROUND', (0,i), (-1,i), LIGHT_RED)
                )

        alert_table.setStyle(TableStyle(row_styles))
        story.append(alert_table)

    story.append(Spacer(1, 16))

    # ── Section 5: Summary stats ──────────────────────────────
    story.append(Paragraph("Case Summary", styles["section_title"]))
    story.append(HRFlowable(width=usable_w, thickness=0.5, color=BORDER, spaceAfter=8))

    new_count  = sum(1 for a in alerts if a.status == "new")
    rev_count  = sum(1 for a in alerts if a.status == "reviewed")
    dis_count  = sum(1 for a in alerts if a.status == "dismissed")
    high_count = sum(1 for a in alerts if (a.confidence or 0) >= 85)
    avg_conf   = (
        sum(a.confidence or 0 for a in alerts) / len(alerts)
        if alerts else 0
    )

    summary_data = [
        [
            Paragraph("Total Alerts",     styles["label"]),
            Paragraph("New / Unreviewed", styles["label"]),
            Paragraph("Reviewed",         styles["label"]),
            Paragraph("Dismissed",        styles["label"]),
            Paragraph("High Confidence",  styles["label"]),
            Paragraph("Avg Confidence",   styles["label"]),
        ],
        [
            Paragraph(str(len(alerts)), ParagraphStyle(
                "sv", fontName="Helvetica-Bold", fontSize=16,
                textColor=DARK_BLUE, alignment=TA_CENTER
            )),
            Paragraph(str(new_count), ParagraphStyle(
                "sv", fontName="Helvetica-Bold", fontSize=16,
                textColor=RED, alignment=TA_CENTER
            )),
            Paragraph(str(rev_count), ParagraphStyle(
                "sv", fontName="Helvetica-Bold", fontSize=16,
                textColor=GREEN, alignment=TA_CENTER
            )),
            Paragraph(str(dis_count), ParagraphStyle(
                "sv", fontName="Helvetica-Bold", fontSize=16,
                textColor=GRAY, alignment=TA_CENTER
            )),
            Paragraph(str(high_count), ParagraphStyle(
                "sv", fontName="Helvetica-Bold", fontSize=16,
                textColor=RED, alignment=TA_CENTER
            )),
            Paragraph(f"{avg_conf:.1f}%", ParagraphStyle(
                "sv", fontName="Helvetica-Bold", fontSize=16,
                textColor=MED_BLUE, alignment=TA_CENTER
            )),
        ]
    ]

    col = usable_w / 6
    summary_table = Table(summary_data, colWidths=[col]*6)
    summary_table.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1, 0), LIGHT_GRAY),
        ('BACKGROUND',    (0,1), (-1,-1), WHITE),
        ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
        ('INNERGRID',     (0,0), (-1,-1), 0.3, BORDER),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 16))

    # ── Section 6: Officer sign-off ───────────────────────────
    story.append(Paragraph("Officer Sign-Off", styles["section_title"]))
    story.append(HRFlowable(width=usable_w, thickness=0.5, color=BORDER, spaceAfter=8))

    signoff_data = [
        [
            Paragraph("Report generated by:", styles["label"]),
            Paragraph("Date:", styles["label"]),
            Paragraph("Case Officer Signature:", styles["label"]),
        ],
        [
            Paragraph(current_user.name, styles["value"]),
            Paragraph(datetime.now().strftime("%d %B %Y"), styles["value"]),
            Paragraph("_________________________", styles["value"]),
        ],
    ]
    col3 = usable_w / 3
    signoff_table = Table(signoff_data, colWidths=[col3]*3)
    signoff_table.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), LIGHT_GRAY),
        ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
        ('INNERGRID',     (0,0), (-1,-1), 0.3, BORDER),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
    ]))
    story.append(signoff_table)
    story.append(Spacer(1, 10))

    # Disclaimer
    story.append(Paragraph(
        "This report is auto-generated by FaceGuard. "
        "All information is confidential and intended for authorized law enforcement use only. "
        "Unauthorized distribution is prohibited.",
        styles["small"]
    ))

    # ── Build PDF ─────────────────────────────────────────────
    filename = f"FaceGuard_Report_{case_ref}.pdf"
    filepath = os.path.join(tempfile.gettempdir(), filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        topMargin=65,
        bottomMargin=70,
        leftMargin=20*mm,
        rightMargin=20*mm,
    )
    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)

    # Cleanup temp image
    if tmp_photo and os.path.exists(tmp_photo):
        os.remove(tmp_photo)

    return FileResponse(
        filepath,
        media_type="application/pdf",
        filename=filename,
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@router.get("/all-persons")
def generate_all_persons_report(
    db: Session = Depends(get_db),
    current_user: User = Depends(require_officer)
):
    """Generate a summary PDF of all missing persons."""

    persons = db.query(MissingPerson).order_by(
        MissingPerson.created_at.desc()
    ).all()

    styles = build_styles()
    story  = []
    w, h   = A4
    usable_w = w - 40*mm

    # Title
    title_data = [[
        Paragraph("MISSING PERSONS REGISTRY", ParagraphStyle(
            "title", fontName="Helvetica-Bold", fontSize=14,
            textColor=DARK_BLUE, alignment=TA_CENTER
        )),
    ]]
    title_table = Table(title_data, colWidths=[usable_w])
    title_table.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), LIGHT_BLUE),
        ('BOX',           (0,0), (-1,-1), 0.5, MED_BLUE),
        ('TOPPADDING',    (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
    ]))
    story.append(title_table)
    story.append(Spacer(1, 12))

    # Summary counts
    missing_count = sum(1 for p in persons if p.status == "missing")
    found_count   = sum(1 for p in persons if p.status == "found")

    count_data = [[
        Paragraph("Total Cases", styles["label"]),
        Paragraph("Currently Missing", styles["label"]),
        Paragraph("Found / Resolved", styles["label"]),
        Paragraph("Report Date", styles["label"]),
    ],[
        Paragraph(str(len(persons)), ParagraphStyle(
            "cv", fontName="Helvetica-Bold", fontSize=18,
            textColor=DARK_BLUE, alignment=TA_CENTER
        )),
        Paragraph(str(missing_count), ParagraphStyle(
            "cv", fontName="Helvetica-Bold", fontSize=18,
            textColor=RED, alignment=TA_CENTER
        )),
        Paragraph(str(found_count), ParagraphStyle(
            "cv", fontName="Helvetica-Bold", fontSize=18,
            textColor=GREEN, alignment=TA_CENTER
        )),
        Paragraph(datetime.now().strftime("%d %b %Y"), ParagraphStyle(
            "cv", fontName="Helvetica-Bold", fontSize=12,
            textColor=GRAY, alignment=TA_CENTER
        )),
    ]]
    col4 = usable_w / 4
    count_table = Table(count_data, colWidths=[col4]*4)
    count_table.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), WHITE),
        ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
        ('INNERGRID',     (0,0), (-1,-1), 0.3, BORDER),
        ('TOPPADDING',    (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
        ('BACKGROUND',    (0,0), (-1,0), LIGHT_GRAY),
    ]))
    story.append(count_table)
    story.append(Spacer(1, 16))

    # All persons table
    story.append(Paragraph("All Cases", styles["section_title"]))
    story.append(HRFlowable(width=usable_w, thickness=0.5, color=BORDER, spaceAfter=8))

    headers = [
        Paragraph("ID",       styles["label"]),
        Paragraph("Name",     styles["label"]),
        Paragraph("Age/Gender", styles["label"]),
        Paragraph("Last Seen", styles["label"]),
        Paragraph("Reported", styles["label"]),
        Paragraph("Status",   styles["label"]),
    ]
    rows = [headers]

    for p in persons:
        status_color = RED if p.status == "missing" else GREEN
        rows.append([
            Paragraph(f"#{p.id}", styles["body"]),
            Paragraph(p.name or "—", styles["body"]),
            Paragraph(
                f"{p.age or '?'} / {p.gender or '?'}",
                styles["body"]
            ),
            Paragraph(p.last_seen_location or "Unknown", styles["body"]),
            Paragraph(
                p.created_at.strftime("%d %b %Y") if p.created_at else "—",
                styles["body"]
            ),
            Paragraph(
                (p.status or "missing").upper(),
                ParagraphStyle("ps", fontName="Helvetica-Bold",
                               fontSize=9, textColor=status_color)
            ),
        ])

    col_widths = [
        usable_w*0.07,
        usable_w*0.22,
        usable_w*0.15,
        usable_w*0.25,
        usable_w*0.15,
        usable_w*0.16,
    ]
    persons_table = Table(rows, colWidths=col_widths, repeatRows=1)
    persons_table.setStyle(TableStyle([
        ('BACKGROUND',     (0,0), (-1,0), DARK_BLUE),
        ('TEXTCOLOR',      (0,0), (-1,0), WHITE),
        ('FONTNAME',       (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',       (0,0), (-1,0), 8.5),
        ('TOPPADDING',     (0,0), (-1,-1), 7),
        ('BOTTOMPADDING',  (0,0), (-1,-1), 7),
        ('LEFTPADDING',    (0,0), (-1,-1), 8),
        ('RIGHTPADDING',   (0,0), (-1,-1), 8),
        ('GRID',           (0,0), (-1,-1), 0.3, BORDER),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [WHITE, LIGHT_GRAY]),
        ('VALIGN',         (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(persons_table)

    # Build
    filename = f"FaceGuard_AllPersons_{datetime.now().strftime('%Y%m%d')}.pdf"
    filepath = os.path.join(tempfile.gettempdir(), filename)
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        topMargin=65,
        bottomMargin=70,
        leftMargin=20*mm,
        rightMargin=20*mm,
    )
    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)

    return FileResponse(
        filepath,
        media_type="application/pdf",
        filename=filename,
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )